import type { Permission } from "./permissions";

export const ROLE_DEFINITIONS = {
  owner: {
    id: "owner",
    name: "Dueño",
    description: "Es propietario de la cuenta, gestiona usuarios y configuración, y tiene visibilidad administrativa total.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "manage_bank_accounts",
      "withdraw_funds",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_payment_links",
      "view_payment_link_details",
      "create_payment_link",
      "update_payment_link",
      "delete_payment_link",
      "export_payment_links",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "create_internal_transfer",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "export_third_party_payments",
      "view_beneficiaries",
      "manage_beneficiaries",
      "create_beneficiary",
      "update_beneficiary",
      "delete_beneficiary",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "create_product",
      "update_product",
      "update_product_status",
      "delete_product",
      "export_products",
      "view_developer_docs",
      "view_api_keys",
      "manage_api_keys",
      "view_webhooks",
      "manage_webhooks",
      "view_webhook_logs",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
      "manage_account_configuration",
      "submit_account_verification",
      "switch_operating_environment",
      "view_users",
      "create_user",
      "update_user",
      "delete_user",
      "assign_roles",
      "manage_role_permissions",
    ] satisfies Permission[],
  },
  admin: {
    id: "admin",
    name: "Administrador",
    description: "Administra usuarios, configuración y operación sin autoridad de revisión sobre pagos.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "manage_bank_accounts",
      "withdraw_funds",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_payment_links",
      "view_payment_link_details",
      "create_payment_link",
      "update_payment_link",
      "delete_payment_link",
      "export_payment_links",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "create_internal_transfer",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "export_third_party_payments",
      "view_beneficiaries",
      "manage_beneficiaries",
      "create_beneficiary",
      "update_beneficiary",
      "delete_beneficiary",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "create_product",
      "update_product",
      "update_product_status",
      "delete_product",
      "export_products",
      "view_developer_docs",
      "view_api_keys",
      "manage_api_keys",
      "view_webhooks",
      "manage_webhooks",
      "view_webhook_logs",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
      "manage_account_configuration",
      "submit_account_verification",
      "switch_operating_environment",
      "view_users",
      "create_user",
      "update_user",
      "delete_user",
      "assign_roles",
    ] satisfies Permission[],
  },
  developer: {
    id: "developer",
    name: "Desarrollador",
    description: "Gestiona llaves API, webhooks y vistas de desarrollo.",
    permissions: [
      "view_dashboard",
      "view_developer_docs",
      "view_api_keys",
      "manage_api_keys",
      "view_webhooks",
      "manage_webhooks",
      "view_webhook_logs",
      "view_account_information",
      "view_account_configuration",
    ] satisfies Permission[],
  },
  finance: {
    id: "finance",
    name: "Finanzas",
    description: "Consulta datos financieros y exporta reportes operativos sin autoridad transaccional.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_payment_links",
      "view_payment_link_details",
      "export_payment_links",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "export_third_party_payments",
      "view_beneficiaries",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "export_products",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
    ] satisfies Permission[],
  },
  operations: {
    id: "operations",
    name: "Operaciones",
    description: "Ejecuta pagos aprobados y gestiona el movimiento operativo de fondos sin poder de aprobación.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "create_internal_transfer",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "execute_third_party_payment",
      "export_third_party_payments",
      "view_beneficiaries",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "view_payment_links",
      "view_payment_link_details",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
    ] satisfies Permission[],
  },
  viewer: {
    id: "viewer",
    name: "Consulta",
    description: "Acceso de solo lectura para monitoreo y trazabilidad.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "view_payments",
      "view_incoming_transfers",
      "view_payment_links",
      "view_payment_link_details",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "view_beneficiaries",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "view_products",
      "view_product_details",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
    ] satisfies Permission[],
  },
  maker: {
    id: "maker",
    name: "Creador",
    description: "Crea, edita y envía pagos a terceros, y gestiona beneficiarios.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "create_internal_transfer",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "create_third_party_payment",
      "update_third_party_payment",
      "submit_third_party_payment",
      "attach_payment_documents",
      "cancel_third_party_payment",
      "export_third_party_payments",
      "view_beneficiaries",
      "manage_beneficiaries",
      "create_beneficiary",
      "update_beneficiary",
      "delete_beneficiary",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "create_product",
      "update_product",
      "update_product_status",
      "delete_product",
      "export_products",
      "view_payment_links",
      "view_payment_link_details",
      "create_payment_link",
      "update_payment_link",
      "delete_payment_link",
      "export_payment_links",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
    ] satisfies Permission[],
  },
  checker: {
    id: "checker",
    name: "Revisor",
    description: "Revisa, aprueba o rechaza pagos sensibles sin capacidad de creación ni ejecución.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_bank_accounts",
      "view_payments",
      "export_payments",
      "view_incoming_transfers",
      "export_incoming_transfers",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "approve_third_party_payment",
      "reject_third_party_payment",
      "export_third_party_payments",
      "view_beneficiaries",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "export_customers",
      "export_customer_history",
      "view_products",
      "view_product_details",
      "view_payment_links",
      "view_payment_link_details",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
    ] satisfies Permission[],
  },
  risk: {
    id: "risk",
    name: "Riesgo / Compliance",
    description: "Supervisa operaciones y auditoría sin capacidad transaccional.",
    permissions: [
      "view_dashboard",
      "view_balance",
      "view_payouts",
      "view_payments",
      "export_payments",
      "view_internal_transfers",
      "view_internal_transfer_details",
      "export_internal_transfers",
      "view_third_party_payments",
      "view_third_party_payment_details",
      "view_third_party_payment_audit",
      "export_third_party_payments",
      "view_beneficiaries",
      "view_customers",
      "view_customer_details",
      "view_customer_history",
      "view_account_information",
      "view_account_configuration",
      "view_account_verification_status",
      "view_users",
    ] satisfies Permission[],
  },
} as const;

export type RoleId = keyof typeof ROLE_DEFINITIONS;

export type RoleDefinition = {
  id: RoleId;
  name: string;
  description: string;
  permissions: Permission[];
};

export const ROLE_LIST: RoleDefinition[] = Object.values(
  ROLE_DEFINITIONS
) as RoleDefinition[];
